#
# Module manifest for module 'ConfigureDefender'
#
# Generated by: RayG
#
# Generated on: 2026-03-11
#

@{
	RootModule        = 'InitialiseModule.psm1'
	ModuleVersion     = '0.1'
	GUID              = 'b4ddb8e6-c93f-4879-9209-31f600ad2a36'
	Author            = 'RayG'
	CompanyName       = 'RayG'
	Copyright         = '(c) 2026 RayG. All rights reserved.'
	Description       = 'Manages Microsoft Defender configuration: ASR rules, exclusions, Controlled Folder Access, Network Protection, and event inspection. Provides a GUI front-end via NamedPipe elevation.'
	PowerShellVersion = '5.0'
	RequiredModules   = @(
		@{
			ModuleName    = 'NamedPipe'
			ModuleVersion = '0.6'
		}
	)
	ModuleList        = @()
	FileList          = @()
	PrivateData       = @{
		ModuleName = 'ConfigureDefender'
		ModuleVars = @{
			''      = @{
				1 = 'DefineVariables.ps1'
			}
			Windows = @{}
			Linux   = @{}
			MacOS   = @{}
		}
	}
}
