#
# Module manifest for module 'ConfigureDefender'
#
# Generated by: RayG
#
# Generated on: 2026-03-11
#

@{
	RootModule        = 'InitialiseModule.psm1'
	ModuleVersion     = '0.4'
	GUID              = 'b4ddb8e6-c93f-4879-9209-31f600ad2a36'
	Author            = 'RayG'
	CompanyName       = 'RayG'
	Copyright         = '(c) 2026 RayG. All rights reserved.'
	Description       = 'Manages Microsoft Defender configuration: ASR rules, exclusions, Controlled Folder Access, Network Protection, and event inspection. Provides a GUI front-end via NamedPipe elevation. v0.4: PSScriptAnalyzer cleanup - 13 exported Get-CD* accessors renamed to singular nouns to match their existing Set-CD* siblings (breaking change, see CHANGELOG.md).'
	PowerShellVersion = '5.0'
	RequiredModules   = @(
		@{
			ModuleName      = 'NamedPipe'
			RequiredVersion = '0.15'
		}
	)
	# Explicit exports so PowerShell can AUTO-LOAD the module on first use of any of
	# these commands (e.g. Start-ConfigureDefenderGUI) without a manual Import-Module.
	# This list MUST mirror the runtime Export-ModuleMember set driven by the
	# FunctionExportTable in Functions\DefineVariables.ps1 - the effective exports are
	# the INTERSECTION of the two, so a name dropped here becomes unavailable.
	FunctionsToExport = @(
		# 2026-09-12 (v0.4): 13 Get-CD* accessors renamed to singular nouns (PSUseSingularNouns
		# cleanup) - each now matches its existing Set-CD* sibling's naming exactly.
		'Get-CDASRRule', 'Get-CDEvent', 'Get-CDControlledFolder', 'Get-CDNetworkProtection',
		'Get-CDControlledFolderAccess', 'Get-CDASRExclusion', 'Get-CDExclusionProcess',
		'Get-CDExclusionPath', 'Get-CDExclusionExtension', 'Get-CDExclusionIpAddress',
		'Get-CDAllowedApplication', 'Get-CDSetting', 'Get-CDThreatAction', 'Get-CDThreatDetection',
		'Set-CDASRRule', 'Set-CDASRExclusion', 'Set-CDExclusionProcess', 'Set-CDExclusionPath',
		'Set-CDExclusionExtension', 'Set-CDExclusionIpAddress', 'Set-CDSetting', 'Set-CDThreatAction',
		'Set-CDControlledFolder', 'Set-CDAllowedApplication', 'Set-CDControlledFolderAccess',
		'Set-CDNetworkProtection', 'Set-CDCIVerbose', 'Open-CDPipeSession', 'Close-CDPipeSession',
		'Get-CDSendRequestParam', 'Test-CDPipeSession', 'Start-ConfigureDefenderGUI',
		# 2026-09-07: vendored catch-audit utilities (replaces the retired self-authored
		# Write-CDCatchAudit/Enable-CDCatchAudit/Disable-CDCatchAudit) - Write-MyCatchAudit itself
		# stays internal, matching VHDTools' identical exception (see Shared-Usage.psd1).
		'Enable-MyCatchAudit', 'Disable-MyCatchAudit', 'Get-MyCatchAuditLog', 'Show-MyCatchAuditSummary',
		'Clear-MyCatchAuditLog', 'Invoke-MyCatchAuditTriage',
		# 2026-09-16: archive-housekeeping pair for Clear-MyCatchAuditLog's own archives (Invoke-FileManagement
		# itself stays internal, same treatment as every other module).
		'Clear-MyCatchAuditArchive',
		# 2026-09-16: function-trace facility, full-module rollout - see Functions\DefineVariables.ps1
		# for the internal-only entries (Write-MyFunctionTrace/Get-MyFunctionTracePath/
		# Format-MyFunctionTraceLine/Invoke-FileManagement) this table's own default-exported
		# convention requires explicit '= $false' for.
		'Enable-MyFunctionTrace', 'Disable-MyFunctionTrace', 'Clear-MyFunctionTraceLog', 'Clear-MyFunctionTraceArchive'
	)
	CmdletsToExport   = @()
	# '*' not @(): the psm1 exports its variable vocabulary via Export-ModuleMember
	# -Variable; a manifest @() filters that to nothing. Autoload runs off
	# FunctionsToExport above independently. (Regression fixed 2026-07-05.)
	VariablesToExport = '*'
	AliasesToExport   = @()
	ModuleList        = @()
	FileList          = @()
	PrivateData       = @{
		ModuleName = 'ConfigureDefender'
		ModuleVars = @{
			''      = @{
				1 = 'DefineVariables.ps1'
			}
			Windows = @{}
			Linux   = @{}
			MacOS   = @{}
		}
	}
}
